// 六十四卦枚举 {label: 卦名, value: 卦序, key: 二进制}
const SIXTY_FOUR_GUA_ENUM = {
  // 上经三十卦
  QIAN: { label: "乾", value: 1, key: "111111", id: "QIAN", trigram: "乾为天" },
  KUN: { label: "坤", value: 2, key: "000000", id: "KUN", trigram: "坤为地" },
  ZHUN: { label: "屯", value: 3, key: "010001", id: "ZHUN", trigram: "水雷屯" },
  MENG: { label: "蒙", value: 4, key: "100010", id: "MENG", trigram: "山水蒙" },
  XU: { label: "需", value: 5, key: "010111", id: "XU", trigram: "水天需" },
  SONG: { label: "讼", value: 6, key: "111010", id: "SONG", trigram: "天水讼" },
  SHI: { label: "师", value: 7, key: "000010", id: "SHI", trigram: "地水师" },
  BI: { label: "比", value: 8, key: "010000", id: "BI", trigram: "水地比" },
  XIAO_CHU: {
    label: "小畜",
    value: 9,
    key: "110111",
    id: "XIAO_CHU",
    trigram: "风天小畜",
  },
  LV: { label: "履", value: 10, key: "111011", id: "LV", trigram: "天泽履" },
  TAI: { label: "泰", value: 11, key: "000111", id: "TAI", trigram: "地天泰" },
  PI: { label: "否", value: 12, key: "111000", id: "PI", trigram: "天地否" },
  TONG_REN: {
    label: "同人",
    value: 13,
    key: "111101",
    id: "TONG_REN",
    trigram: "天火同人",
  },
  DA_YOU: {
    label: "大有",
    value: 14,
    key: "101111",
    id: "DA_YOU",
    trigram: "火天大有",
  },
  QIAN_GUA: {
    label: "谦",
    value: 15,
    key: "000100",
    id: "QIAN_GUA",
    trigram: "地山谦",
  },
  YU: { label: "豫", value: 16, key: "001000", id: "YU", trigram: "雷地豫" },
  SUI: { label: "随", value: 17, key: "100110", id: "SUI", trigram: "泽雷随" },
  GU: { label: "蛊", value: 18, key: "011001", id: "GU", trigram: "山风蛊" },
  LIN: { label: "临", value: 19, key: "000011", id: "LIN", trigram: "地泽临" },
  GUAN: {
    label: "观",
    value: 20,
    key: "110000",
    id: "GUAN",
    trigram: "风地观",
  },
  SHI_HE: {
    label: "噬嗑",
    value: 21,
    key: "100101",
    id: "SHI_HE",
    trigram: "火雷噬嗑",
  },
  BI_GUA: {
    label: "贲",
    value: 22,
    key: "101001",
    id: "BI_GUA",
    trigram: "山火贲",
  },
  BO: { label: "剥", value: 23, key: "000001", id: "BO", trigram: "山地剥" },
  FU: { label: "复", value: 24, key: "100000", id: "FU", trigram: "地雷复" },
  WU_WANG: {
    label: "无妄",
    value: 25,
    key: "100111",
    id: "WU_WANG",
    trigram: "天雷无妄",
  },
  DA_CHU: {
    label: "大畜",
    value: 26,
    key: "111001",
    id: "DA_CHU",
    trigram: "山天大畜",
  },
  YI_GUA: {
    label: "颐",
    value: 27,
    key: "100001",
    id: "YI_GUA",
    trigram: "山雷颐",
  },
  DA_GUO: {
    label: "大过",
    value: 28,
    key: "011110",
    id: "DA_GUO",
    trigram: "泽风大过",
  },
  KAN: { label: "坎", value: 29, key: "010010", id: "KAN", trigram: "坎为水" },
  LI: { label: "离", value: 30, key: "101101", id: "LI", trigram: "离为火" },

  // 下经三十四卦
  XIAN: {
    label: "咸",
    value: 31,
    key: "001110",
    id: "XIAN",
    trigram: "泽山咸",
  },
  HENG: {
    label: "恒",
    value: 32,
    key: "011100",
    id: "HENG",
    trigram: "雷风恒",
  },
  DUN: { label: "遁", value: 33, key: "111100", id: "DUN", trigram: "天山遁" },
  DA_ZHUANG: {
    label: "大壮",
    value: 34,
    key: "001111",
    id: "DA_ZHUANG",
    trigram: "雷天大壮",
  },
  JIN: { label: "晋", value: 35, key: "000101", id: "JIN", trigram: "火地晋" },
  MING_YI: {
    label: "明夷",
    value: 36,
    key: "101000",
    id: "MING_YI",
    trigram: "地火明夷",
  },
  JIA_REN: {
    label: "家人",
    value: 37,
    key: "101011",
    id: "JIA_REN",
    trigram: "风火家人",
  },
  KUI: { label: "睽", value: 38, key: "110101", id: "KUI", trigram: "火泽睽" },
  JIAN: {
    label: "蹇",
    value: 39,
    key: "010100",
    id: "JIAN",
    trigram: "水山蹇",
  },
  XIE: { label: "解", value: 40, key: "001010", id: "XIE", trigram: "雷水解" },
  SUN: { label: "损", value: 41, key: "100011", id: "SUN", trigram: "山泽损" },
  YI_GUA_2: {
    label: "益",
    value: 42,
    key: "110001",
    id: "YI_GUA_2",
    trigram: "风雷益",
  },
  GUAI: {
    label: "夬",
    value: 43,
    key: "111110",
    id: "GUAI",
    trigram: "泽天夬",
  },
  GOU: { label: "姤", value: 44, key: "011111", id: "GOU", trigram: "天风姤" },
  CUI: { label: "萃", value: 45, key: "000110", id: "CUI", trigram: "泽地萃" },
  SHENG: {
    label: "升",
    value: 46,
    key: "011000",
    id: "SHENG",
    trigram: "地风升",
  },
  KUN_GUA: {
    label: "困",
    value: 47,
    key: "010011",
    id: "KUN_GUA",
    trigram: "泽水困",
  },
  JING: {
    label: "井",
    value: 48,
    key: "110010",
    id: "JING",
    trigram: "水风井",
  },
  GE: { label: "革", value: 49, key: "101110", id: "GE", trigram: "泽火革" },
  DING: {
    label: "鼎",
    value: 50,
    key: "011101",
    id: "DING",
    trigram: "火风鼎",
  },
  ZHEN: {
    label: "震",
    value: 51,
    key: "100100",
    id: "ZHEN",
    trigram: "震为雷",
  },
  GEN: { label: "艮", value: 52, key: "001001", id: "GEN", trigram: "艮为山" },
  JIAN_GUA: {
    label: "渐",
    value: 53,
    key: "001011",
    id: "JIAN_GUA",
    trigram: "风山渐",
  },
  GUI_MEI: {
    label: "归妹",
    value: 54,
    key: "110100",
    id: "GUI_MEI",
    trigram: "雷泽归妹",
  },
  FENG: {
    label: "丰",
    value: 55,
    key: "101100",
    id: "FENG",
    trigram: "雷火丰",
  },
  LV_GUA: {
    label: "旅",
    value: 56,
    key: "001101",
    id: "LV_GUA",
    trigram: "火山旅",
  },
  XUN: { label: "巽", value: 57, key: "011011", id: "XUN", trigram: "巽为风" },
  DUI: { label: "兑", value: 58, key: "110110", id: "DUI", trigram: "兑为泽" },
  HUAN: {
    label: "涣",
    value: 59,
    key: "010011",
    id: "HUAN",
    trigram: "风水涣",
  },
  JIE: { label: "节", value: 60, key: "110010", id: "JIE", trigram: "水泽节" },
  ZHONG_FU: {
    label: "中孚",
    value: 61,
    key: "110011",
    id: "ZHONG_FU",
    trigram: "风泽中孚",
  },
  XIAO_GUO: {
    label: "小过",
    value: 62,
    key: "001100",
    id: "XIAO_GUO",
    trigram: "雷山小过",
  },
  JI_JI: {
    label: "既济",
    value: 63,
    key: "010101",
    id: "JI_JI",
    trigram: "水火既济",
  },
  WEI_JI: {
    label: "未济",
    value: 64,
    key: "101010",
    id: "WEI_JI",
    trigram: "火水未济",
  },
};

// 八卦基础枚举
const BA_GUA_ENUM = {
  QIAN: { label: "乾", value: 1, key: "111", trigram: "天", nature: "健" },
  KUN: { label: "坤", value: 2, key: "000", trigram: "地", nature: "顺" },
  ZHEN: { label: "震", value: 3, key: "100", trigram: "雷", nature: "动" },
  XUN: { label: "巽", value: 4, key: "011", trigram: "风", nature: "入" },
  KAN: { label: "坎", value: 5, key: "010", trigram: "水", nature: "陷" },
  LI: { label: "离", value: 6, key: "101", trigram: "火", nature: "丽" },
  GEN: { label: "艮", value: 7, key: "001", trigram: "山", nature: "止" },
  DUI: { label: "兑", value: 8, key: "110", trigram: "泽", nature: "悦" },
};

const SIXTY_FOUR_GUA_ENUM_KEY_MAP = Object.keys(SIXTY_FOUR_GUA_ENUM).reduce(
  (acc, key) => {
    acc[SIXTY_FOUR_GUA_ENUM[key].key] = SIXTY_FOUR_GUA_ENUM[key];
    return acc;
  },
  {}
);

// 六十四卦卦辞枚举
const SIXTY_FOUR_GUA_JICI_ENUM = {
  QIAN: "元亨，利贞。",
  KUN: "元亨，利牝马之贞。",
  ZHUN: "亨。利贞。勿用有攸往，利建侯。",
  MENG: "亨。匪我求童蒙，童蒙求我。初筮告，再三渎，渎则不告。利贞。",
  XU: "有孚，光亨，贞吉。利涉大川。",
  SONG: "有孚，窒惕，中吉，终凶。利见大人，不利涉大川。",
  SHI: "贞，丈人吉，无咎。",
  BI: "亨。小利有攸往。",
  XIAO_CHU: "亨。利贞。",
  LV: "履虎尾，不咥人，亨。",
  TAI: "小往大来，吉亨。",
  PI: "否之匪人，不利君子贞，大往小来。",
  TONG_REN: "同人于野，亨。利涉大川，利君子贞。",
  DA_YOU: "元亨。",
  QIAN_GUA: "利涉大川，先甲三日，后甲三日。",
  YU: "亨。利贞。取女吉。",
  SUI: "元亨利贞。",
  GU: "元亨，利涉大川。先甲三日，后甲三日。",
  LIN: "元亨，利贞。至于八月有凶。",
  GUAN: "盥而不荐，有孚颙若。",
  SHI_HE: "亨。利贞。可涉大川。",
  BI_GUA: "吉。见大人，勿恤。南征吉。",
  BO: "利有攸往，亨。",
  FU: "亨。无咎，利贞。利有攸往。",
  WU_WANG: "元亨，利贞。其匪正有眚，不利有攸往。",
  DA_XU: "利贞。",
  YI: "利有攸往，利涉大川。",
  DA_GUO: "栋桡，利有攸往，亨。",
  KAN: "习坎，有孚，维心亨，行有尚。",
  LI: "利贞，亨。畜牝牛吉。",
  XIAN: "亨。利贞。利有攸往。",
  HENG: "元亨，利贞。利有攸往。",
  DUN: "亨。小利贞。",
  DA_ZHUANG: "利贞。",
  JIN: "康侯用锡马蕃庶，昼日三接。",
  MING_YI: "利艰贞。",
  JIA_REN: "利女贞。",
  KUI: "亨。利涉大川。利君子贞。",
  JIAN: "利西南，不利东北。利见大人，贞吉。",
  XIE: "利西南，无所往，其来复吉。有攸往，夙吉。",
  SUN: "利有攸往，利涉大川。",
  YI_GUA_2: "利有攸往，利涉大川。",
  GUAI: "扬于王庭，孚号有厉。告自邑，不利即戎，利有攸往。",
  GOU: "女壮，勿用取女。",
  CUI: "亨。利涉大川，利贞。",
  SHENG: "元亨，用见大人，勿恤，南征吉。",
  KUN_GUA: "亨。贞大人吉，无咎。有言不信。",
  JING: "元吉，无咎。",
  GE: "己日乃孚。元亨，利贞，悔亡。",
  DING: "元吉。",
  ZHEN: "亨，震来虩虩，笑言哑哑，震惊百里，不丧匕鬯。",
  GEN: "艮其背，不获其身，行其庭，不见其人，无咎。",
  JIAN_GUA: "女归吉，利贞。",
  GUI_MEI: "征凶，无攸利。",
  FENG: "亨，王假之，勿忧，宜日中。",
  LV_GUA: "小亨，旅贞吉。",
  XUN: "小亨，利有攸往，利见大人。",
  DUI: "亨，利贞。",
  HUAN: "亨，王假有庙，利涉大川，利贞。",
  JIE: "苦节不可贞。",
  ZHONG_FU: "豚鱼吉，利涉大川，利贞。",
  XIAO_GUO: "亨。利贞。可小事，不可大事。飞鸟遗之音，不宜上，宜下，大吉。",
  JI_JI: "亨，利贞。两利亡，贞吉，有孚中行，告公用圭。",
  WEI_JI: "亨。小狐汔济，濡其尾，无攸利。",
};

// 生成 六十四卦解卦枚举

// 导出枚举
export {
  SIXTY_FOUR_GUA_ENUM,
  BA_GUA_ENUM,
  SIXTY_FOUR_GUA_ENUM_KEY_MAP,
  SIXTY_FOUR_GUA_JICI_ENUM,
};
